//@version=4
strategy("Bullish Engulfing Pattern", shorttitle="BEP", overlay=true)

bullishEngulfing = close[1] < open[1] and close > open and close > open[1] and open < close[1]

if bullishEngulfing
    strategy.entry("BullishEngulfingLong", strategy.long)

plotshape(bullishEngulfing, title="Bullish Engulfing", location=location.belowbar, color=color.green, style=shape.labelup, text="BE")
